version: '3.1'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: owoidb
            POSTGRES_PASSWORD: privatepassword
        ports:
            - 5432:5432
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        links:
            - postgres
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: privatepassword
        ports:
            - 5050:80
