# Generated by Django 4.1.4 on 2022-12-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clip", models.FileField(upload_to="clips")),
                ("clip_name", models.CharField(max_length=120)),
                ("clip_description", models.TextField()),
                (
                    "clip_thumbnail",
                    models.ImageField(blank=True, upload_to="clip_thumbnails"),
                ),
                ("clip_isPublic", models.BooleanField(default=False)),
                ("clip_views", models.IntegerField(default=0)),
                ("clip_likes", models.IntegerField(default=0)),
                ("clip_image_url", models.CharField(blank=True, max_length=500)),
                ("clip_url_aws", models.CharField(blank=True, max_length=500)),
                ("clip_soundtrack_url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=120, unique=True)),
                ("username", models.CharField(max_length=120, unique=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, upload_to="profile_pictures"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="one_word_one_image.clip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="one_word_one_image.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="one_word_one_image.user",
            ),
        ),
    ]
