# Generated by Django 4.1.4 on 2022-12-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("one_word_one_image", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="one_word_one_image.user",
            ),
        ),
    ]
