# Generated by Django 4.1.6 on 2023-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "one_word_one_image",
            "0002_clip_alter_user_options_alter_user_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="clip",
            field=models.FileField(blank=True, null=True, upload_to="clips"),
        ),
        migrations.AlterField(
            model_name="clip",
            name="clip_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="clip_image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="clip_soundtrack_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="clip",
            name="clip_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="clip_thumbnails"),
        ),
        migrations.AlterField(
            model_name="clip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
